user-message: "WARNING: This stack project is generated."

flags:
  liquid-fixpoint:
    devel: true 
    link-z3-as-a-library: true

resolver: nightly-2023-11-25

# We have 1 package.
packages:
  - ./.

extra-deps:
  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - smtlib-backends-0.3@rev:1
  - smtlib-backends-process-0.3@rev:1
  - smtlib-backends-z3-0.3@rev:1
